UTF-16-encoded User Agents cause DB failure
A user agent string with an interpunct fails to convert correctly to UTF-8 and causes a database error to occur when the Visitor object is saved.

Error:
DataError: invalid byte sequence for encoding "UTF8": 0xb7

META:
'HTTP_USER_AGENT': 'Mozilla/4.0 (compatible; MSIE 6.0; Windows 98; Rogers Hi\xb7Speed Internet; (R1 1.3))',